[2024-01-29 17:32:06,370] {processor.py:153} INFO - Started process (PID=4382) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:32:06,370] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:32:06,371] {logging_mixin.py:115} INFO - [2024-01-29 17:32:06,371] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:32:06,388] {logging_mixin.py:115} INFO - [2024-01-29 17:32:06,386] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 6, in <module>
    start_date = datetime(2024,1,29)
NameError: name 'datetime' is not defined
[2024-01-29 17:32:06,388] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:32:06,405] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.038 seconds
[2024-01-29 17:32:37,007] {processor.py:153} INFO - Started process (PID=4444) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:32:37,009] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:32:37,009] {logging_mixin.py:115} INFO - [2024-01-29 17:32:37,009] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:32:37,024] {logging_mixin.py:115} INFO - [2024-01-29 17:32:37,024] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 6, in <module>
    start_date = datetime(2024,1,29)
NameError: name 'datetime' is not defined
[2024-01-29 17:32:37,025] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:32:37,042] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.039 seconds
[2024-01-29 17:32:57,376] {processor.py:153} INFO - Started process (PID=4488) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:32:57,377] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:32:57,378] {logging_mixin.py:115} INFO - [2024-01-29 17:32:57,378] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:32:57,413] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:32:57,440] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.076 seconds
[2024-01-29 17:33:27,893] {processor.py:153} INFO - Started process (PID=4550) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:33:27,895] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:33:27,895] {logging_mixin.py:115} INFO - [2024-01-29 17:33:27,895] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:33:27,907] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:33:27,917] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.025 seconds
[2024-01-29 17:33:58,209] {processor.py:153} INFO - Started process (PID=4612) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:33:58,210] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:33:58,210] {logging_mixin.py:115} INFO - [2024-01-29 17:33:58,210] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:33:58,224] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:33:58,235] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.029 seconds
[2024-01-29 17:34:28,761] {processor.py:153} INFO - Started process (PID=4674) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:34:28,763] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:34:28,764] {logging_mixin.py:115} INFO - [2024-01-29 17:34:28,764] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:34:28,800] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:34:28,819] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.068 seconds
[2024-01-29 17:34:59,214] {processor.py:153} INFO - Started process (PID=4736) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:34:59,216] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:34:59,216] {logging_mixin.py:115} INFO - [2024-01-29 17:34:59,216] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:34:59,238] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:34:59,263] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.055 seconds
[2024-01-29 17:35:29,592] {processor.py:153} INFO - Started process (PID=4789) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:35:29,593] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:35:29,594] {logging_mixin.py:115} INFO - [2024-01-29 17:35:29,594] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:35:29,627] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:35:29,644] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.057 seconds
[2024-01-29 17:36:00,176] {processor.py:153} INFO - Started process (PID=4851) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:36:00,177] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:36:00,179] {logging_mixin.py:115} INFO - [2024-01-29 17:36:00,179] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:36:00,224] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:36:00,244] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.077 seconds
[2024-01-29 17:36:30,749] {processor.py:153} INFO - Started process (PID=4913) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:36:30,751] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:36:30,752] {logging_mixin.py:115} INFO - [2024-01-29 17:36:30,752] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:36:30,785] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:36:30,805] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.065 seconds
[2024-01-29 17:37:01,076] {processor.py:153} INFO - Started process (PID=4975) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:37:01,078] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:37:01,079] {logging_mixin.py:115} INFO - [2024-01-29 17:37:01,078] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:37:01,110] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:37:01,141] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.073 seconds
[2024-01-29 17:43:45,508] {processor.py:153} INFO - Started process (PID=40) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:43:45,510] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:43:45,513] {logging_mixin.py:115} INFO - [2024-01-29 17:43:45,513] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:43:45,593] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:43:45,665] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.175 seconds
[2024-01-29 17:44:16,165] {processor.py:153} INFO - Started process (PID=102) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:44:16,166] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:44:16,166] {logging_mixin.py:115} INFO - [2024-01-29 17:44:16,166] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:44:16,187] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:44:16,200] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.040 seconds
[2024-01-29 17:44:46,701] {processor.py:153} INFO - Started process (PID=155) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:44:46,702] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:44:46,702] {logging_mixin.py:115} INFO - [2024-01-29 17:44:46,702] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:44:46,723] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:44:46,738] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.041 seconds
[2024-01-29 17:45:17,625] {processor.py:153} INFO - Started process (PID=217) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:45:17,626] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:45:17,627] {logging_mixin.py:115} INFO - [2024-01-29 17:45:17,627] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:45:17,654] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:45:17,672] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.053 seconds
[2024-01-29 17:45:48,383] {processor.py:153} INFO - Started process (PID=279) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:45:48,385] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:45:48,386] {logging_mixin.py:115} INFO - [2024-01-29 17:45:48,386] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:45:48,432] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:45:48,452] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.074 seconds
[2024-01-29 17:45:53,547] {processor.py:153} INFO - Started process (PID=308) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:45:53,548] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:45:53,548] {logging_mixin.py:115} INFO - [2024-01-29 17:45:53,548] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:45:53,551] {logging_mixin.py:115} INFO - [2024-01-29 17:45:53,550] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 30
    )
    ^
SyntaxError: invalid syntax
[2024-01-29 17:45:53,552] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:45:53,568] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.024 seconds
[2024-01-29 17:46:23,784] {processor.py:153} INFO - Started process (PID=361) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:46:23,785] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:46:23,785] {logging_mixin.py:115} INFO - [2024-01-29 17:46:23,785] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:46:23,789] {logging_mixin.py:115} INFO - [2024-01-29 17:46:23,788] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 30
    )
    ^
SyntaxError: invalid syntax
[2024-01-29 17:46:23,790] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:46:23,807] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.028 seconds
[2024-01-29 17:46:53,893] {processor.py:153} INFO - Started process (PID=423) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:46:53,894] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:46:53,894] {logging_mixin.py:115} INFO - [2024-01-29 17:46:53,894] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:46:53,897] {logging_mixin.py:115} INFO - [2024-01-29 17:46:53,896] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 30
    )
    ^
SyntaxError: invalid syntax
[2024-01-29 17:46:53,897] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:46:53,908] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.016 seconds
[2024-01-29 17:47:03,540] {processor.py:153} INFO - Started process (PID=448) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:47:03,541] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:47:03,542] {logging_mixin.py:115} INFO - [2024-01-29 17:47:03,542] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:47:03,566] {logging_mixin.py:115} INFO - [2024-01-29 17:47:03,564] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:47:03,566] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:47:03,594] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.061 seconds
[2024-01-29 17:47:34,290] {processor.py:153} INFO - Started process (PID=510) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:47:34,290] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:47:34,291] {logging_mixin.py:115} INFO - [2024-01-29 17:47:34,291] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:47:34,307] {logging_mixin.py:115} INFO - [2024-01-29 17:47:34,306] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:47:34,307] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:47:34,325] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.040 seconds
[2024-01-29 17:48:05,025] {processor.py:153} INFO - Started process (PID=572) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:48:05,026] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:48:05,027] {logging_mixin.py:115} INFO - [2024-01-29 17:48:05,027] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:48:05,042] {logging_mixin.py:115} INFO - [2024-01-29 17:48:05,041] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:48:05,043] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:48:05,060] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.039 seconds
[2024-01-29 17:48:35,898] {processor.py:153} INFO - Started process (PID=634) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:48:35,898] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:48:35,899] {logging_mixin.py:115} INFO - [2024-01-29 17:48:35,899] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:48:35,911] {logging_mixin.py:115} INFO - [2024-01-29 17:48:35,909] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:48:35,911] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:48:35,930] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.036 seconds
[2024-01-29 17:49:06,232] {processor.py:153} INFO - Started process (PID=687) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:49:06,233] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:49:06,234] {logging_mixin.py:115} INFO - [2024-01-29 17:49:06,233] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:49:06,247] {logging_mixin.py:115} INFO - [2024-01-29 17:49:06,246] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:49:06,248] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:49:06,276] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.048 seconds
[2024-01-29 17:49:36,735] {processor.py:153} INFO - Started process (PID=749) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:49:36,739] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:49:36,739] {logging_mixin.py:115} INFO - [2024-01-29 17:49:36,739] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:49:36,754] {logging_mixin.py:115} INFO - [2024-01-29 17:49:36,753] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:49:36,755] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:49:36,771] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.042 seconds
[2024-01-29 17:49:52,907] {processor.py:153} INFO - Started process (PID=768) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:49:52,908] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:49:52,909] {logging_mixin.py:115} INFO - [2024-01-29 17:49:52,909] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:49:52,928] {logging_mixin.py:115} INFO - [2024-01-29 17:49:52,926] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:49:52,928] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:49:52,945] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.044 seconds
[2024-01-29 17:50:23,408] {processor.py:153} INFO - Started process (PID=822) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:50:23,409] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:50:23,410] {logging_mixin.py:115} INFO - [2024-01-29 17:50:23,409] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:50:23,431] {logging_mixin.py:115} INFO - [2024-01-29 17:50:23,429] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:50:23,431] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:50:23,453] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.058 seconds
[2024-01-29 17:50:51,813] {processor.py:153} INFO - Started process (PID=884) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:50:51,814] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:50:51,814] {logging_mixin.py:115} INFO - [2024-01-29 17:50:51,814] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:50:51,830] {logging_mixin.py:115} INFO - [2024-01-29 17:50:51,829] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:50:51,831] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:50:51,858] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.049 seconds
[2024-01-29 17:51:21,962] {processor.py:153} INFO - Started process (PID=945) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:51:21,964] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:51:21,965] {logging_mixin.py:115} INFO - [2024-01-29 17:51:21,965] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:51:21,980] {logging_mixin.py:115} INFO - [2024-01-29 17:51:21,979] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:51:21,981] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:51:21,997] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.040 seconds
[2024-01-29 17:51:34,805] {processor.py:153} INFO - Started process (PID=988) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:51:34,807] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:51:34,807] {logging_mixin.py:115} INFO - [2024-01-29 17:51:34,807] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:51:34,819] {logging_mixin.py:115} INFO - [2024-01-29 17:51:34,818] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:51:34,819] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:51:34,834] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.032 seconds
[2024-01-29 17:52:04,869] {processor.py:153} INFO - Started process (PID=1051) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:52:04,871] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:52:04,871] {logging_mixin.py:115} INFO - [2024-01-29 17:52:04,871] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:52:04,880] {logging_mixin.py:115} INFO - [2024-01-29 17:52:04,879] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:52:04,880] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:52:04,895] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.028 seconds
[2024-01-29 17:52:35,724] {processor.py:153} INFO - Started process (PID=1114) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:52:35,725] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:52:35,726] {logging_mixin.py:115} INFO - [2024-01-29 17:52:35,726] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:52:35,736] {logging_mixin.py:115} INFO - [2024-01-29 17:52:35,735] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:52:35,736] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:52:35,752] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.032 seconds
[2024-01-29 17:53:06,542] {processor.py:153} INFO - Started process (PID=1167) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:53:06,545] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:53:06,546] {logging_mixin.py:115} INFO - [2024-01-29 17:53:06,546] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:53:06,555] {logging_mixin.py:115} INFO - [2024-01-29 17:53:06,554] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:53:06,555] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:53:06,566] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.030 seconds
[2024-01-29 17:53:22,860] {processor.py:153} INFO - Started process (PID=1187) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:53:22,861] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:53:22,862] {logging_mixin.py:115} INFO - [2024-01-29 17:53:22,862] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:53:22,894] {logging_mixin.py:115} INFO - [2024-01-29 17:53:22,893] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:53:22,895] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:53:22,918] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.063 seconds
[2024-01-29 17:53:53,996] {processor.py:153} INFO - Started process (PID=1248) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:53:54,000] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:53:54,003] {logging_mixin.py:115} INFO - [2024-01-29 17:53:54,003] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:53:54,137] {logging_mixin.py:115} INFO - [2024-01-29 17:53:54,132] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:53:54,138] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:53:54,256] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.284 seconds
[2024-01-29 17:54:24,371] {processor.py:153} INFO - Started process (PID=1310) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:54:24,372] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:54:24,372] {logging_mixin.py:115} INFO - [2024-01-29 17:54:24,372] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:54:24,405] {logging_mixin.py:115} INFO - [2024-01-29 17:54:24,404] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:54:24,406] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:54:24,433] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.068 seconds
[2024-01-29 17:54:54,532] {processor.py:153} INFO - Started process (PID=1363) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:54:54,533] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:54:54,535] {logging_mixin.py:115} INFO - [2024-01-29 17:54:54,535] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:54:54,556] {logging_mixin.py:115} INFO - [2024-01-29 17:54:54,555] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:54:54,556] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:54:54,596] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.070 seconds
[2024-01-29 17:55:24,696] {processor.py:153} INFO - Started process (PID=1425) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:55:24,698] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:55:24,698] {logging_mixin.py:115} INFO - [2024-01-29 17:55:24,698] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:55:24,713] {logging_mixin.py:115} INFO - [2024-01-29 17:55:24,712] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/get_price_FB.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_price_FB.py", line 14, in <module>
    tags = tags
TypeError: __init__() got an unexpected keyword argument 'shedule_interval'
[2024-01-29 17:55:24,714] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:55:24,733] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.042 seconds
[2024-01-29 17:55:51,737] {processor.py:153} INFO - Started process (PID=1487) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:55:51,738] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:55:51,738] {logging_mixin.py:115} INFO - [2024-01-29 17:55:51,738] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:55:51,777] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:55:51,791] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.058 seconds
[2024-01-29 17:56:22,186] {processor.py:153} INFO - Started process (PID=1540) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:56:22,187] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:56:22,188] {logging_mixin.py:115} INFO - [2024-01-29 17:56:22,188] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:56:22,225] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:56:22,265] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.090 seconds
[2024-01-29 17:56:52,429] {processor.py:153} INFO - Started process (PID=1602) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:56:52,431] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:56:52,432] {logging_mixin.py:115} INFO - [2024-01-29 17:56:52,432] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:56:52,498] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:56:52,551] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.130 seconds
[2024-01-29 17:57:23,299] {processor.py:153} INFO - Started process (PID=1664) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:57:23,300] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:57:23,301] {logging_mixin.py:115} INFO - [2024-01-29 17:57:23,301] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:57:23,325] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:57:23,342] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.049 seconds
[2024-01-29 17:57:53,420] {processor.py:153} INFO - Started process (PID=1726) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:57:53,422] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:57:53,422] {logging_mixin.py:115} INFO - [2024-01-29 17:57:53,422] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:57:53,439] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:57:53,449] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.032 seconds
[2024-01-29 17:58:24,483] {processor.py:153} INFO - Started process (PID=1779) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:58:24,485] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:58:24,486] {logging_mixin.py:115} INFO - [2024-01-29 17:58:24,486] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:58:24,510] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:58:24,527] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.051 seconds
[2024-01-29 17:58:54,730] {processor.py:153} INFO - Started process (PID=1840) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:58:54,732] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:58:54,733] {logging_mixin.py:115} INFO - [2024-01-29 17:58:54,732] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:58:54,752] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:58:54,766] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.039 seconds
[2024-01-29 17:59:25,628] {processor.py:153} INFO - Started process (PID=1902) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:59:25,629] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:59:25,630] {logging_mixin.py:115} INFO - [2024-01-29 17:59:25,630] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:59:25,681] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:59:25,707] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.087 seconds
[2024-01-29 17:59:56,528] {processor.py:153} INFO - Started process (PID=1964) to work on /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:59:56,529] {processor.py:641} INFO - Processing file /opt/airflow/dags/get_price_FB.py for tasks to queue
[2024-01-29 17:59:56,530] {logging_mixin.py:115} INFO - [2024-01-29 17:59:56,530] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:59:56,559] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/get_price_FB.py
[2024-01-29 17:59:56,575] {processor.py:161} INFO - Processing /opt/airflow/dags/get_price_FB.py took 0.062 seconds
